"""Added user role

Revision ID: 52f420fa5288
Revises: a85ec2668edc
Create Date: 2024-07-18 15:29:31.262102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52f420fa5288'
down_revision = 'a85ec2668edc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.drop_column('role')
        batch_op.drop_column('password')

    # ### end Alembic commands ###
