"""Add created_by_id column to Song

Revision ID: 550594b286ff
Revises: c3e0d0753af9
Create Date: 2024-07-31 23:11:43.967167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550594b286ff'
down_revision = 'c3e0d0753af9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites_authors', schema=None) as batch_op:
        batch_op.drop_constraint('favorites_authors_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorites_authors_author_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'authors', ['author_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('favorites_songs', schema=None) as batch_op:
        batch_op.drop_constraint('favorites_songs_song_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorites_songs_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'songs', ['song_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['created_by_id'], ['id'])

    with op.batch_alter_table('user_song_settings', schema=None) as batch_op:
        batch_op.drop_constraint('user_song_settings_user_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('user_song_settings_song_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'songs', ['song_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_song_settings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_song_settings_song_id_fkey', 'songs', ['song_id'], ['id'])
        batch_op.create_foreign_key('user_song_settings_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('songs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('status')
        batch_op.drop_column('created_by_id')

    with op.batch_alter_table('favorites_songs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites_songs_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('favorites_songs_song_id_fkey', 'songs', ['song_id'], ['id'])

    with op.batch_alter_table('favorites_authors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites_authors_author_id_fkey', 'authors', ['author_id'], ['id'])
        batch_op.create_foreign_key('favorites_authors_user_id_fkey', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
