"""Password > Password_hash

Revision ID: 57063b72aadf
Revises: 52f420fa5288
Create Date: 2024-07-18 16:22:49.590173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57063b72aadf'
down_revision = '52f420fa5288'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=150), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
